#///////////////////////////////////////////////////////////////////////////////
#// Reaper
#//
#// Copyright (c) 2015-2020 Thibault Schueller
#// This file is distributed under the MIT License
#///////////////////////////////////////////////////////////////////////////////

clone_folder: c:\project\reaper
os:
    - Visual Studio 2017
    - Visual Studio 2019
platform:
    - x64
configuration:
    - Debug
    - Release
environment:
    repo_folder: 'c:\project\reaper'
install:
    # Appveyor does not clone git submodules by default
    # See https://github.com/appveyor/ci/issues/899
    - cmd: git submodule update --init --recursive
    - ps: cmake --version
    - ps: .\tools\ci\install_vulkan_sdk.ps1
build_script:
    - ps: cmake .\ -Bbuild -DREAPER_BUILD_SHARED_LIBRARIES=OFF -DREAPER_GIT_HOOKS_AUTO_UPDATE=OFF -DREAPER_RUN_CLANG_TIDY=OFF
    - ps: cmake --build build --config %CONFIGURATION%
    - ps: cmake .\ -Bbuild -DREAPER_BUILD_SHARED_LIBRARIES=ON -DREAPER_GIT_HOOKS_AUTO_UPDATE=OFF -DREAPER_RUN_CLANG_TIDY=OFF
    - ps: cmake --build build --config %CONFIGURATION%
    - ps: cmake --build build --target RUN_TESTS
