#///////////////////////////////////////////////////////////////////////////////
#// Reaper
#//
#// Copyright (c) 2015-2018 Thibault Schueller
#// This file is distributed under the MIT License
#///////////////////////////////////////////////////////////////////////////////

clone_folder: c:\project\reaper
os:
    - Visual Studio 2015
platform:
    - x64
environment:
    repo_folder: 'c:\project\reaper'
install:
# Appveyor does not clone git submodules by default
# See https://github.com/appveyor/ci/issues/899
    - cmd: git submodule update --init --recursive
    - ps: cmake --version
    - ps: .\tools\ci\install_vulkan_sdk.ps1
build_script:
    - ps: cmake .\ -Bbuild -G "Visual Studio 14 2015 Win64" -DREAPER_GIT_HOOKS_AUTO_UPDATE=OFF -DREAPER_RUN_CLANG_TIDY=OFF
    - ps: cmake --build build --config Debug
    - ps: cmake --build build --target RUN_TESTS
