#///////////////////////////////////////////////////////////////////////////////
#// Reaper
#//
#// Copyright (c) 2015-2020 Thibault Schueller
#// This file is distributed under the MIT License
#///////////////////////////////////////////////////////////////////////////////

sudo: required
services:
    - docker
language: cpp
env:
    global:
        - DOCKER_IMAGE=ubuntu-19.04
        - DOCKER_CONTAINER=builder
install:
    - cp tools/ci/${DOCKER_IMAGE}/Dockerfile .
    - docker build . -t ${DOCKER_IMAGE}
    - docker run -i -d --name=${DOCKER_CONTAINER} -v $(pwd):/repo ${DOCKER_IMAGE}
script:
    - docker exec ${DOCKER_CONTAINER} cmake -H/repo -B/build-static -DREAPER_BUILD_SHARED_LIBRARIES=OFF -DREAPER_GIT_HOOKS_AUTO_UPDATE=OFF -DREAPER_RUN_CLANG_TIDY=OFF
    - docker exec ${DOCKER_CONTAINER} cmake --build /build-static
    - docker exec ${DOCKER_CONTAINER} cmake -H/repo -B/build-dynamic -DREAPER_BUILD_SHARED_LIBRARIES=ON -DREAPER_GIT_HOOKS_AUTO_UPDATE=OFF -DREAPER_RUN_CLANG_TIDY=OFF
    - docker exec ${DOCKER_CONTAINER} cmake --build /build-dynamic
    - docker exec ${DOCKER_CONTAINER} cmake --build /build-dynamic --target test
    #- docker exec ${DOCKER_CONTAINER} pushd build && ctest --output-on-failure && popd
