////////////////////////////////////////////////////////////////////////////////
/// Reaper
///
/// Copyright (c) 2015-2022 Thibault Schueller
/// This file is distributed under the MIT License
////////////////////////////////////////////////////////////////////////////////

// Generated by CMake

#pragma once

#include "core/Compiler.h"

#if defined(REAPER_BUILD_SHARED)
#    if defined(NEPTUNE_SIM_EXPORT)
#        define NEPTUNE_SIM_API REAPER_EXPORT
#    else
#        define NEPTUNE_SIM_API REAPER_IMPORT
#    endif
#elif defined(REAPER_BUILD_STATIC)
#    define NEPTUNE_SIM_API
#else
#    error "Build type must be defined"
#endif
