////////////////////////////////////////////////////////////////////////////////
/// Reaper
///
/// Copyright (c) 2015-2021 Thibault Schueller
/// This file is distributed under the MIT License
////////////////////////////////////////////////////////////////////////////////

// Generated by CMake

#pragma once

#define REAPER_VERSION_MAJOR 0
#define REAPER_VERSION_MINOR 1
#define REAPER_VERSION_PATCH 0
#define REAPER_VERSION "0.1.0"
