# This script is there to warm up the git LFS cache every so often so that it doesn't get removed after 7 days.
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
name: Refresh LFS Cache
on:
  workflow_dispatch: # Allow the action to be manually triggered
  schedule:
    # Run on Monday and Friday at 10:00 UTC
    - cron: '0 10 * * 1,5'

jobs:
  refresh_lfs_cache:
    runs-on: '${{ matrix.runner }}'
    # We can't use a list on 'runs-on' so we declare a matrix instead.k
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
    name: "Refresh git LFS cache"
    steps:
      # NOTE: It's important that the options specified here are the same as the common build action.
      # Failing that, we'll get a different cache key and it won't work.
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          submodules: true
