////////////////////////////////////////////////////////////////////////////////
/// Reaper
///
/// Copyright (c) 2015-2022 Thibault Schueller
/// This file is distributed under the MIT License
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "Window.h"

#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>

// Generated by wayland-scanner at build time
#include "xdg-shell-client-protocol.h"

namespace Reaper
{
class REAPER_RENDERER_API WaylandWindow : public IWindow
{
public:
    WaylandWindow(const WindowCreationDescriptor& creationInfo);
    ~WaylandWindow();

    void       map() override final;
    void       unmap() override final;
    void       pumpEvents(std::vector<Window::Event>& eventOutput) override final;
    MouseState get_mouse_state() override final;

public:
    // Exposed for Vulkan surface creation
    wl_display* m_display;
    wl_surface* m_surface;

    // Wayland globals
    wl_registry*   m_registry;
    wl_compositor* m_compositor;
    xdg_wm_base*   m_xdg_wm_base;
    wl_seat*       m_seat;

    // Per-window XDG objects
    xdg_surface*  m_xdg_surface;
    xdg_toplevel* m_xdg_toplevel;

    // Input objects
    wl_pointer*  m_pointer;
    wl_keyboard* m_keyboard;

    // xkbcommon keyboard state
    xkb_context* m_xkb_context;
    xkb_keymap*  m_xkb_keymap;
    xkb_state*   m_xkb_state;

    // Tracked state
    i32  m_mouse_x;
    i32  m_mouse_y;
    bool m_configured;

    // Set only during pumpEvents(); callbacks write here
    std::vector<Window::Event>* m_event_output;
};
} // namespace Reaper
